export const CURRENCY_LOCALES: Record<string, string> = {
  USD: 'en-US',
  EUR: 'de-DE',
  GBP: 'en-GB',
  CAD: 'en-CA',
  BRL: 'pt-BR',
  AUD: 'en-AU',
  JPY: 'ja-JP',
  CNY: 'zh-CN',
  INR: 'en-IN',
  CHF: 'de-CH',
  NZD: 'en-NZ',
  SGD: 'en-SG',
  HKD: 'zh-HK',
  MXN: 'es-MX',
  ZAR: 'en-ZA',
  NGN: 'en-NG',
  EGP: 'ar-EG',
  KES: 'en-KE',
  GHS: 'en-GH',
  MAD: 'ar-MA',
  TZS: 'en-TZ',
  UGX: 'en-UG',
  DZD: 'ar-DZ',
  TND: 'ar-TN',
  ETB: 'am-ET',
  XOF: 'fr-SN',
  XAF: 'fr-CM',
  RWF: 'rw-RW',
  MUR: 'en-MU',
  SEK: 'sv-SE',
  NOK: 'no-NO',
  DKK: 'da-DK',
  RUB: 'ru-RU',
  TRY: 'tr-TR',
  AED: 'ar-AE',
  SAR: 'ar-SA',
  ILS: 'he-IL',
  PLN: 'pl-PL',
  ARS: 'es-AR',
  CLP: 'es-CL',
  COP: 'es-CO',
};

export const SUPPORTED_CURRENCIES = [
  { code: 'USD', label: 'USD ($)', symbol: '$' },
  { code: 'EUR', label: 'EUR (€)', symbol: '€' },
  { code: 'GBP', label: 'GBP (£)', symbol: '£' },
  { code: 'CAD', label: 'CAD (C$)', symbol: 'C$' },
  { code: 'BRL', label: 'BRL (R$)', symbol: 'R$' },
  { code: 'AUD', label: 'AUD (A$)', symbol: 'A$' },
  { code: 'JPY', label: 'JPY (¥)', symbol: '¥' },
  { code: 'CNY', label: 'CNY (¥)', symbol: '¥' },
  { code: 'INR', label: 'INR (₹)', symbol: '₹' },
  { code: 'CHF', label: 'CHF (Fr)', symbol: 'Fr' },
  { code: 'NZD', label: 'NZD (NZ$)', symbol: 'NZ$' },
  { code: 'SGD', label: 'SGD (S$)', symbol: 'S$' },
  { code: 'HKD', label: 'HKD (HK$)', symbol: 'HK$' },
  { code: 'MXN', label: 'MXN ($)', symbol: '$' },
  { code: 'ZAR', label: 'ZAR (R)', symbol: 'R' },
  { code: 'NGN', label: 'NGN (₦)', symbol: '₦' },
  { code: 'EGP', label: 'EGP (ج.م)', symbol: 'ج.م' },
  { code: 'KES', label: 'KES (KSh)', symbol: 'KSh' },
  { code: 'GHS', label: 'GHS (GH₵)', symbol: 'GH₵' },
  { code: 'MAD', label: 'MAD (DH)', symbol: 'DH' },
  { code: 'TZS', label: 'TZS (TSh)', symbol: 'TSh' },
  { code: 'UGX', label: 'UGX (USh)', symbol: 'USh' },
  { code: 'DZD', label: 'DZD (DA)', symbol: 'DA' },
  { code: 'TND', label: 'TND (DT)', symbol: 'DT' },
  { code: 'ETB', label: 'ETB (Br)', symbol: 'Br' },
  { code: 'XOF', label: 'XOF (CFA)', symbol: 'CFA' },
  { code: 'XAF', label: 'XAF (FCFA)', symbol: 'FCFA' },
  { code: 'RWF', label: 'RWF (FRw)', symbol: 'FRw' },
  { code: 'MUR', label: 'MUR (Rs)', symbol: 'Rs' },
  { code: 'SEK', label: 'SEK (kr)', symbol: 'kr' },
  { code: 'NOK', label: 'NOK (kr)', symbol: 'kr' },
  { code: 'DKK', label: 'DKK (kr)', symbol: 'kr' },
  { code: 'RUB', label: 'RUB (₽)', symbol: '₽' },
  { code: 'TRY', label: 'TRY (₺)', symbol: '₺' },
  { code: 'AED', label: 'AED (د.إ)', symbol: 'د.إ' },
  { code: 'SAR', label: 'SAR (ر.س)', symbol: 'ر.س' },
  { code: 'ILS', label: 'ILS (₪)', symbol: '₪' },
  { code: 'PLN', label: 'PLN (zł)', symbol: 'zł' },
  { code: 'ARS', label: 'ARS ($)', symbol: '$' },
  { code: 'CLP', label: 'CLP ($)', symbol: '$' },
  { code: 'COP', label: 'COP ($)', symbol: '$' },
];

export const formatMoney = (amount: number, currency: string = 'USD') => {
  const locale = CURRENCY_LOCALES[currency.toUpperCase()] || 'en-US';
  return new Intl.NumberFormat(locale, {
    style: 'currency',
    currency: currency.toUpperCase(),
  }).format(amount);
};
